TugasAkhirPTI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_page.urls')),
    path('friends/', include('add_friends.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

add_friends/urls.py
from . import views
from django.urls import path

app_name = 'add_friends'

urlpatterns = [
    path('', views.friends_list , name='friends_list'),
    path('create_friends/', views.create_friends , name="create_friends"),
    path('details/<int:id>', views.friends_details , name="details"), 
    path('create_comments/<int:id>/', views.create_comments , name="create_comment"),        
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='portfolio_page'
urlpatterns = [
    path('', views.index, name='homepage'),
]

accounts/models.py
from django.db import models

# Create your models here.

add_friends/models.py
from django.db import models
from django.contrib.auth.models import User

class Friends(models.Model):
    nama = models.CharField(max_length=100)
    deskripsi = models.TextField()
    idLine = models.CharField(max_length=50)
    TTL = models.CharField(max_length=80)  
    author = models.ForeignKey(User,default=None,  on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return self.nama

class Comment(models.Model):
    comment = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    friend = models.ForeignKey(Friends, on_delete=models.CASCADE, blank=True, null=True, related_name="comment")
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return "{} - {}".format(self.author, self.comment)

portfolio_page/models.py
from django.db import models

# Create your models here.

add_friends/forms.py
from . import models
from django import forms

class CreateFriends(forms.ModelForm):
    class Meta:
        model = models.Friends #models yang kita gunakan dari models.py
        fields = [
            'nama','deskripsi','idLine','TTL',
        ]

class CreateComments(forms.ModelForm):
    class Meta:
        model = models.Comment 
        fields = [
            'comment',
        ]

accounts/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('portfolio_page:homepage')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method =="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('portfolio_page:homepage')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('portfolio_page:homepage')

add_friends/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from. models import Friends, Comment
from. import forms
# Create your views here.

def friends_list(request):
    friends = Friends.objects.all().order_by('nama')
    return render(request, 'add_friends/list_friends.html', {'friends':friends})

def friends_details(request, id):
    friends = Friends.objects.get(id = id)
    comment_form = forms.CreateComments()
    return render(request, 'add_friends/friends_details.html', {'friends': friends, 'comment_form':comment_form})

@login_required(login_url="/accounts/login")
def create_friends(request):
    if request.method == 'POST':
        form = forms.CreateFriends(request.POST)
        if form.is_valid():
            #save data into database
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('add_friends:friends_list') #name of the URL

    else:
        form = forms.CreateFriends()
    return render(request, 'add_friends/create_friends.html', {'form':form})

@login_required(login_url="/accounts/login")
def create_comments(request, id):
    comment_form = forms.CreateComments(request.POST)
    friend = Friends.objects.get(id = id)
    if request.method=="POST" and comment_form.is_valid():
        instance = comment_form.save(commit=False)
        instance.author = request.user
        instance.friend = friend
        instance.save()
    return redirect('add_friends:details', id = id)

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'portfolio_page/profile.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="accounts-view">
        <h1>Log In</h1>
        <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            {{ form  }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input type="submit" value="Log In">
        </form>
        <h5>Don't have an account?</h5>
        <h5>Please sign-up first <button type="submit"><a href="{% url 'accounts:signup' %}">Sign Up</a></button></h5>
        

    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="accounts-view">
        <h1>Sign Up</h1>
        <form class="site-form" action="/accounts/signup/" method="POST">
            {% csrf_token %}
            {{ form  }}
            <input type="submit" value="Sign Up">
        </form>
        <h5>Already have an account?</h5>
        <h5>Just login! <button type="submit"><a href="{% url 'accounts:login' %}">Login</a></button></h5>
    </div>
{% endblock %}

add_friends/templates/add_friends/create_friends.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-friends">
    <h2>Let's be a friend!</h2>
    <form class="site-form" action="{% url 'add_friends:create_friends' %}" method="post">
        {% csrf_token %}
        {{ form }} 
        <input type="submit" value="Create">
    </form>
</div>


{% endblock %}

add_friends/templates/add_friends/friends_details.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="friends_details">
    <div class="friends">
        <p>Nama         : {{ friends.nama }}</p>
        <p>Deskripsi    : {{ friends.deskripsi }}</p>
        <p>TTL          : {{ friends.TTL }}</p>
        <p>Id Line      : {{ friends.idLine }}</p>
    </div>
    <div class="comments">
        <div> 
            <h2>Write Comments here!</h2>
            <form method="POST" action="{% url 'add_friends:create_comment' id=friends.id %}">
                    {% csrf_token %}
                    <div>
                        {% for field in comment_form.visible_fields %}
                            {{ field }}
                        {% endfor %}
                        <button type="submit">Comment</button>
                    </div>
            </form>
        </div>

        <div>
            <h2>Comments:</h2>
            {% for comment in friends.comment.all %}
                <div>
                    <p>{{ comment.comment }} by {{ comment.author.username }}, {{comment.created_at}}</p>
                </div>
            {% endfor %}
        </div>
   
    </div>
</div>
{% endblock %}

add_friends/templates/add_friends/list_friends.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Friends List</h1>
    {% for friend in friends %}
        <div class="friends_list">
            <h2><a href="{% url 'add_friends:details' id=friend.id %}">Nama : {{ friend.nama }}</a></h2>
            <p>Tempat, Tanggal Lahir : {{ friend.TTL }}</p>
        </div>
    {% endfor %}
{% endblock %}

portfolio_page/templates/portfolio_page/profile.html
{% extends 'base_layout.html' %}


{% block content %}
{% load static from staticfiles %}
        <div class="container">
            <div class="container">
                <h1>Christopher Tamba</h1>
                <h2>I can do all things because of God in me</h2>
                <img class="photo" src="{% static 'portfolio_page/Christo.jpg' %}">
            </div>
            <div class="container leftContainer">
                <div>
                    <h2>Hello,</h2>
                    <h2>Welcome to my website!</h2>
                    <h2>I was born on 11 February 2001</h2>
                    <h2>Having interests in Gadget, Korean Pop Music, and Sports.  </h2>
                    <h2>A reliable person. A night thinker. A trustworthy person. A discipline person. A responsible person.</h2>
                </div>
                <br><br><br>
                <div class="container">
                    <h2>Contact me!</h2>
                    <div class="container imageContainer">
                        <div class="container">
                            <img class="photo smPhoto" src="{% static 'portfolio_page/Line.png' %}"> 
                            <h3>christamba</h3>
                        </div>
                        <div class="container">
                            <img class="photo smPhoto" src="{% static 'portfolio_page/email.png' %}">
                            <h3>christamba11@gmail.com</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'portfolio_page/style.css' %}">
    <title>Profile</title>
</head>
<body>
    <div class="container">
        <div class="container">
            <ul class="ul">
                <li class="li"><a href="{% url 'portfolio_page:homepage' %}">Home</a></li>
                <li class="li"><a href="{% url 'add_friends:create_friends' %}">Add Friend</a></li>
                <li class="li"><a href="{% url 'add_friends:friends_list' %}">Friends</a></li>
                {% if user.is_authenticated %}
                <li class="li">
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Log Out</button>
                    </form> 
                </li>
                {% else %}
                <li class="li"><a href="{% url 'accounts:login' %}">Login</a></li>
                <li class="li"><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>

        {% block content %}


        {% endblock %}
    </div>


</body>
</html>